name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-activate-base: false
    - name: Add conda to system path
      run: echo "/usr/share/miniconda/condabin" >> $GITHUB_PATH
    - name: Create environment and install dependencies
      run: |
        conda env create --file environment.yml
        echo "conda activate sheetbuddy-env" >> $GITHUB_ENV
        source $GITHUB_ENV
        conda install -y flake8 pytest
    - name: Lint with flake8
      run: |
        source $GITHUB_ENV
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        source $GITHUB_ENV
        pytest
